"use client";

import { useCallback, useRef, useState, type MouseEvent } from "react";
import { useExplorerStore } from "@/store/explorerStore";
import ShellTerminal, { ShellTerminalHandle } from "./ShellTerminal";
import { IconChevronDown, IconClose, IconPlus, IconTrash } from "./icons";

interface TerminalFile {
  name: string;
  content: string;
}

interface TerminalPanelProps {
  projectId: string;
  files: TerminalFile[];
  onWaveformAvailable?: (url: string) => void;
}

interface TerminalTab {
  id: string;
  label: string;
}

// Start at 1: the always-present initial tab is "term-1"/"bash 1" (a static
// literal below, not generated by this counter -- see nextTab() for why).
let tabCounter = 1;
function nextTab(): TerminalTab {
  tabCounter += 1;
  return { id: `term-${tabCounter}`, label: `bash ${tabCounter}` };
}

const INITIAL_TAB: TerminalTab = { id: "term-1", label: "bash 1" };

/** Owns the VS Code-style terminal tab strip: each tab is an independent
 * ShellTerminal instance (own WebSocket, own isolated Docker container, own
 * shell/history). Every tab stays mounted for its whole lifetime -- switching
 * tabs only toggles which one is visible -- so backgrounded sessions keep
 * running and their scrollback is preserved exactly like the collapse/expand
 * behavior ShellTerminal already had.
 *
 * The initial tab is a static literal rather than `nextTab()`: React's Strict
 * Mode double-invokes a useState lazy initializer on the client (but not on
 * the server), so calling a function with a side effect (incrementing a
 * module-level counter) from inside one produces "bash 1" server-side vs
 * "bash 2" client-side -- a hydration mismatch. `nextTab()` is only called
 * from the "+" button's click handler below, which React never double-invokes. */
export default function TerminalPanel({ projectId, files, onWaveformAvailable }: TerminalPanelProps) {
  const [tabs, setTabs] = useState<TerminalTab[]>(() => [INITIAL_TAB]);
  const [activeId, setActiveId] = useState(() => INITIAL_TAB.id);
  const [collapsed, setCollapsed] = useState(false);
  const handles = useRef(new Map<string, ShellTerminalHandle>());

  // Every project switch closes every live terminal session server-side
  // (see explorerStore.ts's resetTerminalWorkspaceBeforeSwitch) -- without
  // this, a switch would leave every open tab quietly showing
  // "[session ended]" until someone noticed and manually opened a new one.
  // Folding this into each tab's key forces a full remount (fresh
  // ShellTerminal, fresh WebSocket) for all of them the moment it happens,
  // by which point the new project's tree is already the one they'll seed
  // from -- see the callers of bumpTerminalGeneration for why this is only
  // bumped *after* that tree is fully applied, not while the switch is
  // still in flight.
  const terminalResetGeneration = useExplorerStore((s) => s.terminalResetGeneration);

  const handleAddTab = useCallback(() => {
    const tab = nextTab();
    setTabs((prev) => [...prev, tab]);
    setActiveId(tab.id);
  }, []);

  const handleCloseTab = useCallback(
    (id: string, event: MouseEvent) => {
      event.stopPropagation();
      setTabs((prev) => {
        if (prev.length <= 1) return prev; // always keep at least one terminal open
        const idx = prev.findIndex((t) => t.id === id);
        const next = prev.filter((t) => t.id !== id);
        handles.current.delete(id);
        if (id === activeId) {
          setActiveId((next[idx - 1] ?? next[0]).id);
        }
        return next;
      });
    },
    [activeId]
  );

  const handleClear = useCallback(() => {
    handles.current.get(activeId)?.clear();
  }, [activeId]);

  return (
    <div className="flex h-full flex-col bg-terminal-bg">
      <div className="flex shrink-0 items-center justify-between border-b border-panel-border bg-surface-sunken px-2 py-1.5">
        <div className="flex min-w-0 flex-1 items-center gap-2 overflow-x-auto">
          <span className="shrink-0 pl-2 text-xs font-semibold tracking-wide text-text-secondary">TERMINAL</span>
          <div className="flex items-center gap-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveId(tab.id)}
                className={`group flex shrink-0 items-center gap-1.5 rounded border px-2 py-0.5 text-[11px] transition-colors duration-200 ${
                  tab.id === activeId
                    ? "border-panel-border bg-surface-hover text-text-primary"
                    : "border-transparent text-text-muted hover:bg-surface-2"
                }`}
              >
                {tab.label}
                {tabs.length > 1 && (
                  <span
                    role="button"
                    tabIndex={-1}
                    onClick={(event) => handleCloseTab(tab.id, event)}
                    aria-label={`Close ${tab.label}`}
                    className="rounded p-0.5 text-text-muted opacity-0 hover:bg-surface-hover hover:text-text-primary group-hover:opacity-100"
                  >
                    <IconClose className="h-2.5 w-2.5" />
                  </span>
                )}
              </button>
            ))}
          </div>
          <button
            type="button"
            onClick={handleAddTab}
            aria-label="New terminal"
            className="shrink-0 rounded-md p-1 text-text-muted transition-colors duration-200 hover:bg-surface-hover hover:text-text-primary"
          >
            <IconPlus className="h-3.5 w-3.5" />
          </button>
        </div>
        <div className="flex shrink-0 items-center gap-1">
          <button
            type="button"
            onClick={handleClear}
            aria-label="Clear terminal"
            className="rounded-md p-1.5 text-text-muted transition-colors duration-200 hover:bg-surface-hover hover:text-text-primary"
          >
            <IconTrash className="h-3.5 w-3.5" />
          </button>
          <button
            type="button"
            onClick={() => setCollapsed((v) => !v)}
            aria-label={collapsed ? "Expand terminal" : "Collapse terminal"}
            className="rounded-md p-1.5 text-text-muted transition-colors duration-200 hover:bg-surface-hover hover:text-text-primary"
          >
            <IconChevronDown className={`h-3.5 w-3.5 transition-transform ${collapsed ? "-rotate-90" : ""}`} />
          </button>
        </div>
      </div>

      <div className="min-h-0 flex-1">
        {tabs.map((tab) => (
          <ShellTerminal
            key={`${tab.id}-${terminalResetGeneration}`}
            ref={(handle) => {
              if (handle) handles.current.set(tab.id, handle);
              else handles.current.delete(tab.id);
            }}
            projectId={projectId}
            files={files}
            generation={terminalResetGeneration}
            active={tab.id === activeId && !collapsed}
            onWaveformAvailable={onWaveformAvailable}
          />
        ))}
      </div>
    </div>
  );
}
