/** Deliberately a plain, static list rather than a full ISO-3166 dependency
 * -- this is a "where are you roughly based" field, not billing/compliance
 * data, so a curated common-countries list is enough. */
export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "India",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Sweden",
  "Switzerland",
  "Spain",
  "Italy",
  "Poland",
  "Portugal",
  "Brazil",
  "Mexico",
  "Argentina",
  "Japan",
  "South Korea",
  "China",
  "Singapore",
  "Taiwan",
  "Israel",
  "United Arab Emirates",
  "Saudi Arabia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "New Zealand",
  "Vietnam",
  "Indonesia",
  "Philippines",
  "Malaysia",
  "Thailand",
  "Pakistan",
  "Bangladesh",
  "Turkey",
  "Russia",
  "Ukraine",
  "Finland",
  "Norway",
  "Denmark",
  "Belgium",
  "Austria",
  "Czech Republic",
  "Romania",
  "Greece",
] as const;
